import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

// 1. Scene Setup
const container = document.getElementById('canvas-container');
const scene = new THREE.Scene();

// 2. Camera Setup (Isometric Angle)
const aspect = window.innerWidth / window.innerHeight;
const frustumSize = 4.5;
const camera = new THREE.OrthographicCamera(
    -frustumSize * aspect,
    frustumSize * aspect,
    frustumSize,
    -frustumSize,
    0.1,
    100
);

// Position camera at isometric angle (similar to Blender camera at (8.5, -8.5, 8.5))
camera.position.set(6, 6, 6);
camera.lookAt(0, 0.4, 0);

// 3. Renderer Setup
const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.0;
container.appendChild(renderer.domElement);

// 4. Orbit Controls
const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.05;
controls.maxPolarAngle = Math.PI / 2 - 0.05; // Prevent camera going below floor
controls.minDistance = 2;
controls.maxDistance = 15;
controls.target.set(0, 0.4, 0);

// 5. Ambient Fill Light (very soft just to avoid black back-faces if any)
const ambientLight = new THREE.AmbientLight(0xffffff, 0.15);
scene.add(ambientLight);

// 6. Load Baked GLB Model
const loader = new GLTFLoader();
const loaderPercent = document.getElementById('loader-percent');
const loaderOverlay = document.getElementById('loader');

let roomModel = null;
let isRotating = false;

// Use the baked combined GLB generated by the Blender script
loader.load(
    '/room_baked_combined.glb',
    (gltf) => {
        roomModel = gltf.scene;
        
        // Traverse and apply settings
        roomModel.traverse((child) => {
            if (child.isMesh) {
                // Ensure the baked material renders unlit and colors pop perfectly
                if (child.material) {
                    child.material.toneMapped = false;
                }
            }
        });
        
        // Center the room model
        roomModel.position.set(0, 0, 0);
        scene.add(roomModel);
        
        // Hide Loader
        loaderOverlay.style.opacity = '0';
        setTimeout(() => {
            loaderOverlay.style.display = 'none';
        }, 600);
    },
    (xhr) => {
        if (xhr.total > 0) {
            const percent = Math.round((xhr.loaded / xhr.total) * 100);
            loaderPercent.textContent = `LOADING 3D ROOM: ${percent}%`;
        }
    },
    (error) => {
        console.error('Error loading GLB:', error);
        loaderPercent.textContent = 'ERROR LOADING MODEL';
    }
);

// 7. Resize Handler
window.addEventListener('resize', () => {
    const newAspect = window.innerWidth / window.innerHeight;
    camera.left = -frustumSize * newAspect;
    camera.right = frustumSize * newAspect;
    camera.top = frustumSize;
    camera.bottom = -frustumSize;
    camera.updateProjectionMatrix();
    
    renderer.setSize(window.innerWidth, window.innerHeight);
});

// 9. Animation Loop
const clock = new THREE.Clock();

function animate() {
    requestAnimationFrame(animate);
    
    const delta = clock.getDelta();
    
    // Slow, smooth auto-rotation
    if (isRotating && roomModel) {
        roomModel.rotation.y += delta * 0.15;
    }
    
    controls.update();
    renderer.render(scene, camera);
}

animate();
